/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ues.api.plataformacursos;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class AppTest {

    @Test
    void contextLoads() {
        // Si el contexto de Spring Boot carga correctamente, la prueba pasa.
        // No se necesita ninguna aserción explícita.
    }
}
