/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ues.api.plataformacursos;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
    }
}
